# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 011f0a757cc150b85567e40cd3865d896147a62c7001fb46dc71dc24dd328588a8b97535d55bc594e79180b0ebf699be88cddd840719add9e0548bd077ba3eac

test:
  secret_key_base: d45d9b15c2c0bf9e94dfbc12d94b0d681b4dcd9ac54daacaff023a16873adcbc0980cbc1f33bd71c1d236d4d365343058eeaacc3fa12e2f5a0662d28579370dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
